[build]
    base = "/"

[[redirects]]
    from = "index*"
    to = "example.html"
    status = 301
    force = true

[[redirects]]
    from = "/"
    to = "example.html"
    status = 301
    force = true
